# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: Default
strategy:
  matrix:    
    Python3:
      python.version: '3'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python3 -m pip install --upgrade pip
    pip3 install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python3 iptv.py
    curl -o epg.xml https://github.com/GreekTVApp/epg-greece-cyprus/releases/download/EPG/epg.xml
    mv iptv.m3u8 tv/iptv.m3u8
    mv epg.xml tv/epg.xml

- script: |
     git add .
     git commit -am "fresh m3u8 and epg"
     git push production master
  displayName: 'Commit and push'
